### ISSUE TITLE
Design Material

### ISSUE THREAD

**Issue by Metroxe** [Frame-One-Software/frame-one-table#2]
- [ ] Social Peview - 1280×640px for best display (e.g. https://github.com/Frame-One-Software/frame-one-table/settings/og-template)
- [ ] Logo as SVG (white/dark theme)
- [ ] Logo as PNG
  - [ ] white background
  - [ ] dark background
  - [ ] transparent background for each above

**Comment by JERRYJURR** [comment]
[frame_one_table_graphics.zip](https://github.com/Frame-One-Software/frame-one-table/files/6819399/frame_one_table_graphics.zip)
